// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 默认根据 docs 文件夹结构自动生成侧边栏。
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
